package se.marketplace.notifications;

/**
 * What signup asks for.
 *
 * <p>Separate from {@link Notifier} rather than three more methods on it. That
 * one is about a booking and takes a {@code BookingNotice}; these are about an
 * address that has not been proved to belong to anyone yet, and forcing them
 * into the same shape would mean a record with a nullable everything.
 *
 * <p>Same discipline though: events that happened, not emails to send, and a
 * dedupe key on every one because the callers are retried.
 */
public interface SignupNotifier {

	/**
	 * Someone asked to register, and we need to know the address is theirs.
	 *
	 * <p>The link is the credential. It is generated by the caller and passed in
	 * rather than built here, because the token behind it is written to the
	 * database in the same transaction as this message and only the caller is
	 * inside that transaction.
	 */
	void verificationRequested(String email, String salonName, String verifyUrl, String dedupeKey);

	/**
	 * Someone tried to register an address that already has an account.
	 *
	 * <p>This message exists because the endpoint cannot say so. Answering
	 * differently for a known address turns the signup form into a way to ask
	 * which salons are on the platform, so the response is identical and the
	 * difference is told only to the mailbox that owns the address.
	 *
	 * <p>Which also means it has to be genuinely useful to a person who did not
	 * try to sign up: it says what happened and offers a way in, and never
	 * implies they did something wrong.
	 */
	void alreadyRegistered(String email, String dedupeKey);

	/**
	 * The salon exists now, and there is a list of things only they can do.
	 *
	 * @param calPassword the Cal account's password, or null when the account
	 *        already existed from an earlier attempt. Sent once and never stored
	 *        in plain text on our side — see {@link #welcome}'s caller
	 */
	void welcome(String email, String salonName, String calUsername, String calPassword,
		String kycUrl, String dedupeKey);

}
